services:
  devopsdemo:
    image: mosazhaw/devopsdemo
    container_name: devopsdemo
    ports:
      - "8088:8080"
    networks:
      - devops_network

  selenium-chrome:
    image: selenium/standalone-chrome:4.26.0
    container_name: selenium-chrome
    shm_size: "2g"
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - devops_network
    depends_on:
      - devopsdemo

networks:
  devops_network:
    driver: bridge
